#%RAML 1.0 Library
usage: Traits

traits:

  seguranca:
    headers:
      
      client_id:
        type: string
        required: true
      client_secret:
        type: string
        required: true