#%RAML 1.0 Library
usage: Types

types:
  getAccountResponse: !include /schemas/getAccount/response.json

  createAccountRequest: !include /schemas/createAccount/request.json
  createAccountResponse: !include /schemas/createAccount/response.json

  findUserRequest: !include /schemas/findUser/request.json
  findUserResponse: !include /schemas/findUser/response.json